package:
  name: aat_analysis
  version: 0.0.4
source:
  sha256: a7a0665600dfee4bea127a0001fc86852d0b14cf76c83370e8abe5145258ca5f
  url: https://files.pythonhosted.org/packages/67/6c/39def8758c9546a2c753abdf26b7018cc3268859664c612d87afd6b1f389/aat_analysis-0.0.4.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes mobile AAT data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
test:
  imports:
  - aat_analysis
