package:
  name: aat_analysis
  version: 0.0.5
source:
  sha256: d8f28942836d6cc22739ae8c0d4e39523dd645eae4a150b43c46dd425b5db88a
  url: https://files.pythonhosted.org/packages/2b/48/d4e1c57eafae46514e7a6b15febc3659989ee520204f56f3f891b619c181/aat_analysis-0.0.5.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes mobile AAT data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
test:
  imports:
  - aat_analysis
