package:
  name: aat_analysis
  version: 0.0.2
source:
  sha256: 611821cdf8228342afbf29cbd70cb33a26cbdeb9680dbfa32d5c36406de014b2
  url: https://files.pythonhosted.org/packages/a7/40/35f9282e3915c56868d8323255f502db00a5a941f9e022ee5284fe5c8d3c/aat_analysis-0.0.2.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes mobile AAT data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
test:
  imports:
  - aat_analysis
