package:
  name: aat_analysis
  version: 0.0.6
source:
  sha256: 22f9558d47b362b7f8418d02cdee679d53fd8b189965e53088cab03cf4b64a13
  url: https://files.pythonhosted.org/packages/e6/f8/9a25bfa73b80cb309b56af2f5c3d00fefd8a20f9bd37b6419c3a432ff5f7/aat_analysis-0.0.6.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes mobile AAT data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
test:
  imports:
  - aat_analysis
