package:
  name: aat_analysis
  version: 0.0.3
source:
  sha256: b0d7ec2f18ac077f6b59bc705f4b3467315a03127e3d936cf7f6edf2344c921a
  url: https://files.pythonhosted.org/packages/01/1b/2f3d53c30e9b274aba200ba29429b9a8550b6f90bdccf7f7e680f3b1911a/aat_analysis-0.0.3.tar.gz
about:
  dev_url: https://hgzech.github.io
  doc_url: https://hgzech.github.io
  home: https://hgzech.github.io
  license: Apache Software
  license_family: APACHE
  summary: This project analyzes mobile AAT data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - hgzech
requirements:
  host:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - scipy
  - pandas
  - tqdm
  - peakutils
  - matplotlib
test:
  imports:
  - aat_analysis
